version: '3'

services:
  flask:
    restart: always
    build: ./cv_maker_shorturl
    env_file: 
      - .env
    links:
      - postgres
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    links:
      - flask:flask

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "2410"
      POSTGRES_DB: "login"
