version: '3'

services:
  flask:
    container_name: flask_api
    restart: always
    build: ./cv_maker_shorturl
    env_file: 
      - .env
    links:
      - postgres
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      docker-network:
        aliases:
          - flask_webapp

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    networks:
      - docker-network

  postgres:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "2410"
      POSTGRES_DB: "login"
networks:
    docker-network:
