version: '3'

services:
  cv_maker_shorturl:
    restart: always
    build: ./cv_maker_shorturl
    expose:
      - "8000"
    env_file: 
      - .env
    links:
      - db

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    links:
      - cv_maker_shorturl:cv_maker_shorturl

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "2410"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "login"\
